#!/bin/bash

for node in $@
do
	echo "***********$node"
	port=`docker-compose -p pg exec $node env | grep -Po "NODE_PORT=\K\d+"`
	docker-compose -p pg exec $node psql --port $port wmc_loyalty postgres -c "select pg_current_xlog_location();"
done
